In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
import pickle
import os

In [34]:
df = pd.read_csv('dia.csv')
print(df.columns)

Index(['Glucose', 'Age'], dtype='object')


In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 2 columns):
Glucose    953 non-null int64
Age        953 non-null int64
dtypes: int64(2)
memory usage: 15.0 KB


In [36]:
df.head(10)

Glucose  Age
0      100   21
1      100   21
2      101   21
3      102   21
4      102   21
5      102   21
6      105   21
7      108   21
8      108   21
9      109   21

In [38]:
df.corr().T

Glucose      Age
Glucose  1.00000  0.21397
Age      0.21397  1.00000

In [39]:
import sklearn
from sklearn.neural_network import MLPClassifier

In [40]:
bins = [0,140,199,300]
group_names =['0','1','2']
df['Output'] = pd.cut(df['Glucose'],bins,labels = group_names)
df = df.dropna(subset=['Output'])
df['Output'] = df['Output'].astype(int)

In [41]:
print(df.groupby('Output').size())

Output
0    335
1    322
2    287
dtype: int64


In [42]:
df.head(10)

Glucose  Age  Output
0      100   21       0
1      100   21       0
2      101   21       0
3      102   21       0
4      102   21       0
5      102   21       0
6      105   21       0
7      108   21       0
8      108   21       0
9      109   21       0

In [43]:
x=df[["Glucose"]]
y=df[["Output"]]


In [44]:
from sklearn.model_selection import train_test_split

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size =0.2,random_state=66)

In [46]:
x_train.shape

(755, 1)

In [47]:
y_train.shape

(755, 1)

In [48]:
clf = MLPClassifier(hidden_layer_sizes=(51),solver="lbfgs",alpha=1e-5)

In [49]:
clf.fit(x,y)

C:\Users\ashish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


MLPClassifier(alpha=1e-05, hidden_layer_sizes=51, solver='lbfgs')

In [50]:
y_pred = clf.predict(x_train)

In [51]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train,y_pred))

1.0


In [ ]:
print(Classification_report(y_train,y_pred))

In [54]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train,y_pred))

[[278   0   0]
 [  0 256   0]
 [  0   0 221]]


In [64]:
a=clf.predict(([[200]]))

In [65]:
if a==0:
    print("you are diabetic free")
    
elif a==1:
    print("you are prediabetic")
    
else:
    print("you are diabetic patient")


you are diabetic patient


In [ ]:
#To save the model

In [31]:
from joblib import dump, load
dump(clf, 'Diebetic.joblib') 

['Diebetic.joblib']

In [32]:
clf = load('asthma.joblib') 

In [66]:
import pickle
with open('dibetic_pickle','wb') as file:
    pickle.dump(clf,file)

In [67]:
with open('dibetic_pickle','rb') as file:
    mp = pickle.load(file)